### ISSUE TITLE
UTF-8 text input?

### ISSUE THREAD

**Issue by DJm00n** [cor3ntin/utf8-windows-demo#1]
UTF-8 text input is great! But what about UTF-8 text input? Is it working?

**Comment by cor3ntin** [comment]
Yes
```
SetConsoleCP(CP_UTF8); // set the input
SetConsoleOutputCP(CP_UTF8); // set the output
```

**Comment by DJm00n** [comment]
Output working fine on my PC but input is broken for non-ASCII: getting '\0' instead of UTF-8 chars. 
Code: https://gist.github.com/DJm00n/52797bbc37760ff40b5e4e8926007e6f
Dafault cmd.exe:
![image](https://user-images.githubusercontent.com/1285934/69144708-8b061e80-0ad4-11ea-8746-67260bab4777.png)
PowerShell in Windows Terminal (Beta):
![image](https://user-images.githubusercontent.com/1285934/69144561-36fb3a00-0ad4-11ea-968d-413b5da55109.png)
cmd.exe in Windows Terminal (Beta):
![image](https://user-images.githubusercontent.com/1285934/69144627-5b571680-0ad4-11ea-8b9a-29ebb97c5396.png)
Windows 1903, MSVS 16.3.9, SDK 10.0.18362.0.

**Comment by DJm00n** [comment]
https://nullprogram.com/blog/2020/05/04/
Seems [ReadConsoleW()](https://docs.microsoft.com/windows/console/readconsole) is the only option currently on Windows to input UTF-16 text. No UTF-8 so far.
